# Generated by Django 5.0.3 on 2024-05-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pensionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('num_cnssap', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('pin', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositaire', models.CharField(max_length=100)),
                ('montant_en_cdf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('etat', models.CharField(max_length=20)),
                ('pensionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussdsimulator.pensionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pensionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussdsimulator.pensionnaire')),
            ],
        ),
    ]
