# Generated by Django 5.0.3 on 2024-05-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdsimulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlevel',
            name='confirm_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
